sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: wuCEODlxhqf22vQTuZ7uGUKz034O86Qd9gqqoCzrElFaxkFyG8muvJIYG5dK7kL726re/pgOzXTVZ2Jqci5yAKV1+D7CEQKFOMAEO2UrCK8RlEg8XJ6SWUSrMIO4reW34l0sC9jq5kWb0EuW7wBOZ2nYart+cGlrtbvW+qlkSegXyE6LASUr4iFZk3WGsCeOVGjI0uJIc7R1Y8zlXAfiQGzy0kOXfSCumGk7zUBbIUcvsIU/RBXxCiwAdb78xKxPPM3ancluTnra3KyP1CzwXchfVNzj1qOp40VONLPu0LR9CVVkBmpa53Qjq3Xwhd/MUFohF+AIkwd0fc9XeUD6PcEhYjL7PlfgdSAW+OlqPrhVB+ao1cxHgtsh3nlmB0j4GjUMTsgRGmIuYAiK6P822ZjNCceK9mAOYCKApY3bsKeP2WhmealgMUV+IMWXFy1GXX9xLfG5nL0nv6bew7zn3NdzEdM1uxMzZHK+brQNctVL8goYTesodmSweWs1u1yuPvAMSULNybVGCHHEjSrSIJw1XdvJoqQ78FnpyA1vsdgSodFe0HY1ejiOUp76Its0t9SZarCc55H4cJNuulymzLb7oufCIzl/sW6zqZipWYLfDVPr5dtRX5RfQEPSauw8i6jvUPd9RbZfV8LVNHiHg+pvcosYLG7J+E1QvqjB2FE=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Taken-Alive_5320
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy